version: '3.8'

services:
  api-db:
    image: postgres:14-alpine
    container_name: api-db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api